export VUE_APP_API_IP="http://localhost:8000/1.0"
export VUE_APP_UNIVERSITY_NAME="Universidad Tecnológica Nacional"
export VUE_APP_FACULTY_NAME="Facultad Regional Paraná"
export VUE_APP_SECRETARY_NAME="Secretaría de Extensión Universitaria y Cultura"
export VUE_APP_AUTHOR="Marcos Huck"
export VUE_APP_AUTHOR_LINK="https://marcos.huck.com.ar"